/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tw_kuoe0_androidjnitest_JNIMethod */

#ifndef _Included_tw_kuoe0_androidjnitest_JNIMethod
#define _Included_tw_kuoe0_androidjnitest_JNIMethod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tw_kuoe0_androidjnitest_JNIMethod
 * Method:    getStringFromNativeForStaticFunction
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_tw_kuoe0_androidjnitest_JNIMethod_getStringFromNativeForStaticFunction
  (JNIEnv *, jclass);

/*
 * Class:     tw_kuoe0_androidjnitest_JNIMethod
 * Method:    getStringFromNativeForMemberFunction
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_tw_kuoe0_androidjnitest_JNIMethod_getStringFromNativeForMemberFunction
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
